channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=23.3.1
- pip:
  - mlflow==2.14.3
  - cloudpickle==3.0.0
  - fsspec==2024.6.1
  - importlib-metadata==7.0.0
  - matplotlib==3.7.4
  - numpy==1.24.4
  - packaging==23.2
  - pandas==1.5.3
  - plotly==5.18.0
  - protobuf==4.25.1
  - psutil==5.9.6
  - pyyaml==6.0.1
  - tensorboard==2.14.0
  - torch==1.13.1
  - xarray==2022.12.0
name: mlflow-env
