name: push

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
      with:
        version: 1.3.1
        virtualenvs-in-project: false
        virtualenvs-path: ~/.virtualenvs

    - name: Install dependencies
      run: poetry install

    - name: Test with pytest
      run: poetry run pytest tests

  check-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
      with:
        version: 1.3.1
        virtualenvs-in-project: false
        virtualenvs-path: ~/.virtualenvs

    - name: Install dependencies
      run: poetry install

    - name: Check Format
      run: poetry run pre-commit run --all-files
